packages:
  - docs
  - scripts
  - apps/cli
  - apps/previ
  - apps/banner
  - packages/test-descriptors
  - packages/tui-test
  - config/neovim
  - config/tmux
  - config/vale
  - config/ideavim
  - config/zsh
