/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface LogSchema {
  /**
   * The version of the protocol.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "log";
  /**
   * The log level.
   */
  level: "debug" | "info" | "warn" | "error";
  /**
   * The log message.
   */
  message: string;
  /**
   * Optional data associated with the log message.
   */
  data?: {
    /**
     * The path to the file being processed when the log message was created.
     */
    "related.path"?: string;
    /**
     * The path to the file the log message originates from.
     */
    "origin.path"?: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
