/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RejectSchema {
  /**
   * The version of the protocol.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "reject";
  /**
   * A human-readable message explaining why the start message was rejected.
   */
  reason: string;
  /**
   * An optional array of capabilities that the client should try instead.
   */
  capabilities: string[];
}
