/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ShutdownSchema {
  /**
   * The version of the protocol.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "shutdown";
  /**
   * A human-readable message explaining why the shutdown was requested.
   */
  reason: string;
  /**
   * An optional status code indicating the reason for the shutdown.
   */
  code: number;
}
