/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface UpdateFilesystemSchema {
  /**
   * The version of the protocol to use.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "update_filesystem";
  updates: (
    | {
        /**
         * Create a new file.
         */
        action: "create";
        /**
         * The path to the new file.
         */
        path: string;
        content:
          | {
              /**
               * The type of content.
               */
              type: "base64";
              /**
               * The base64 encoded contents of the file.
               */
              base64: string;
              /**
               * The encoding the file was originally encoded with.
               */
              originalEncoding: "utf8";
            }
          | {
              /**
               * The type of content.
               */
              type: "gzip";
              /**
               * The gzip encoded contents of the file.
               */
              gzip: string;
              /**
               * The encoding the file was originally encoded with.
               */
              originalEncoding: "utf8";
            }
          | {
              /**
               * The type of content.
               */
              type: "read_file";
              /**
               * The path to the file to read for the content
               */
              read_file: string;
            };
      }
    | {
        /**
         * Update an existing file.
         */
        action: "update";
        /**
         * The path to the file to update.
         */
        path: string;
        content:
          | {
              /**
               * The type of content.
               */
              type: "base64";
              /**
               * The base64 encoded contents of the file.
               */
              base64: string;
              /**
               * The encoding the file was originally encoded with.
               */
              originalEncoding: "utf8";
            }
          | {
              /**
               * The type of content.
               */
              type: "gzip";
              /**
               * The gzip encoded contents of the file.
               */
              gzip: string;
              /**
               * The encoding the file was originally encoded with.
               */
              originalEncoding: "utf8";
            }
          | {
              /**
               * The type of content.
               */
              type: "read_file";
              /**
               * The path to the file to read for the content
               */
              read_file: string;
            };
      }
    | {
        /**
         * Delete a file.
         */
        action: "delete";
        /**
         * The path to the file to delete.
         */
        path: string;
      }
    | {
        /**
         * Rename a file.
         */
        action: "rename";
        /**
         * The path to the file to rename.
         */
        path: string;
        /**
         * The new path for the file.
         */
        newPath: string;
      }
  )[];
}
