/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InitSchema {
  /**
   * The version of the protocol supported by the script.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "init";
  /**
   * An array of supported capabilities.
   */
  capabilities: string[];
}
