/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PreviewRejectSchema {
  /**
   * The version of the protocol.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "preview_reject";
  /**
   * A human-readable message explaining why the preview process was rejected.
   */
  reason: string;
  /**
   * The path of the file that is rejected to be previewed.
   */
  path: string;
}
