/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PreviewAcknowledgeSchema {
  /**
   * The version of the protocol.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "preview_acknowledge";
  /**
   * A human-readable message indicating the start of the preview process.
   */
  message: string;
  /**
   * The path to the file that is starting to be previewed.
   */
  path: string;
}
