/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PreviewCompleteSchema {
  /**
   * The version of the protocol.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "preview_complete";
  /**
   * A human-readable message indicating the successful completion of the preview process.
   */
  message: string;
  /**
   * The path of the file that is being previewed.
   */
  path: string;
}
