/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RequestPreviewSchema {
  /**
   * The version of the protocol to use.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "request_preview";
  /**
   * The path to the file to preview.
   */
  path: string;
  /**
   * Whether to enable live updates (re-render and re-present on file changes).
   */
  liveUpdate?: boolean;
}
