/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface StartSchema {
  /**
   * The version of the protocol to use.
   */
  protocolVersion: string;
  /**
   * The type of the message.
   */
  messageType: "start";
  /**
   * An array of capabilities to enable.
   */
  capabilities: string[];
}
