[package]
name = "banner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
colorchoice = "1.0.4"
colored = "3.0.0"
figlet-rs = "0.1.5"
terminal_size = "0.4.3"
