name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build release
        run: cargo build --release

      - name: Test release
        run: cargo test --release

      - name: Get Rust toolchain version
        id: rust-version
        run: echo "rust_version=$(cargo --version | awk '{print $2}')" >> $GITHUB_ENV

      - name: Upload release artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: rafaeltab-${{ env.rust_version }}-${{ runner.os }}
          path: |
            target/release/rafaeltab # replace with your binary name or path to artifacts
